### ISSUE TITLE
image input for channel changing

### ISSUE THREAD

**Issue by gaoshjjj** [NVlabs/GCVit#17]
what is the input shape ,B H W C or B C H W?

**Comment by ahatamiz** [comment]
Hi @gaoshjjj 

The input shape is the standard `(B C H W)`. The repository is built on top of timm and the model can be integrated with any existing similar workflow.

Best,

**Comment by gaoshjjj** [comment]
> 
Thanks for your answer.I notice that the output shape is (B H W C), how can I transpose it to (B C H W), because I need compose GCVit with FPN.

**Comment by ahatamiz** [comment]
Hi @gaoshjjj , 

I see. We provide helper functions for converting to channel last ([here](https://github.com/NVlabs/GCVit/blob/main/models/gc_vit.py#L18)) and channel first ([here](https://github.com/NVlabs/GCVit/blob/main/models/gc_vit.py#L29)) formats. In your case, the conversion can be done using `_to_channel_first(x)` to meet the downstream tasks requirements. 

Best,
