### ISSUE TITLE
Reliable comparison with Swin: fixed window size

### ISSUE THREAD

**Issue by shkarupa-alex** [NVlabs/GCVit#22]
I believe most architectural ideas in GCViT will boost performance, but i'd like to know reliable differences in metrices.
At the moment it is not possible due to all models trained with unusual window size. 

More precisely Swin V1 with 224x222 input trained with window_size=7 for all stages.
GCViT at the same time uses [7, 7, 14, 7] window sizes. So at the third stage it has twice larger receptive field.

Due to this code branch https://github.com/NVlabs/GCVit/blob/main/models/gc_vit.py#L503 i believe you made some experiments.
Could you please publish their results, so we can understand what part of performance gained by architectural changes and what by receptive field expansion?

**Comment by ahatamiz** [comment]
We have conducted comprehensive ablation studies and verified that all components used the GC ViT enhance the performance. These will be added to our updated arXiv paper in the future. Regarding the window size, the performance is very robust, though it sometimes (for some model variants) lead to negligible accuracy loss.
