### ISSUE TITLE
Backbone Feature Maps for One-Stage Detectors

### ISSUE THREAD

**Issue by sarmientoj24** [NVlabs/GCVit#32]
I was trying to implement GCVit as backbone for YOLO one stage detector. However, one thing I noticed is that YOLO architectures uses only **three feature maps** from its backbone before it passes it to the neck architecture. Howevr, ViT like GCVit and Swin-T have 4 feature maps. How do I properly use these feature maps without loss of vital informations?

**Comment by ahatamiz** [comment]
Hi @sarmientoj24 

This is an interesting scenario. What are the resolutions used for extracting these feature maps ?

Best

**Comment by sarmientoj24** [comment]
Feature maps from Swin-T are like this
```
torch.Size([24, 96, 160, 160])
torch.Size([24, 192, 80, 80])
torch.Size([24, 384, 40, 40])
torch.Size([24, 768, 20, 20])
```

and the neck + head for one stage detectors often use the last three.

**Comment by ahatamiz** [comment]
We should be able to accommodate for this. Please stay tuned for the detection code. 

Ali

**Comment by ross-Hr** [comment]
@sarmientoj24  
you can change like this :

```
 downsample=(i <= len(depths) - 1),   

in 

level = GCViTLayer(dim=int(dim * 2 ** i),
                               depth=depths[i],
                               num_heads=num_heads[i],
                               window_size=window_size[i],
                               mlp_ratio=mlp_ratio,
                               qkv_bias=qkv_bias,
                               qk_scale=qk_scale,
                               drop=drop_rate, attn_drop=attn_drop_rate,
                               drop_path=dpr[sum(depths[:i]):sum(depths[:i + 1])],
                               norm_layer=norm_layer,
                               downsample=(i <= len(depths) - 1),
                               layer_scale=layer_scale,
                               input_resolution=int(2 ** (-2 - i) * resolution),
                               image_resolution=resolution)  
```

**Comment by ahatamiz** [comment]
We have released the [detection](https://github.com/NVlabs/GCVit/tree/main/detection) code. Hopefully it could be useful.
