### ISSUE TITLE
Is there any documentation to train a semantic segmentation model using a custom dataset?

### ISSUE THREAD

**Issue by pablojrios** [NVlabs/GCVit#36]
Hi,

1. How can I train a semantic segmentation model using a custom dataset by fine-tuning a pretrained segmentation model?
2. As a follow-up question, are there pretrained segmentation models available to fine-tune it using a custom dataset?

Thank you.

**Comment by ahatamiz** [comment]
Hi @pablojrios 

Thanks for the comment. Currently, we support arbitrary sized image resolutions with arbitrary window sizes for down-stream fine-tuning including ADE20K semantics segmentation. Hence, any custom fine-tuning should be possible. We will release the segmentation code and pre-trained models very soon. 

Best,

**Comment by AkankshaKaple** [comment]
Hi @ahatamiz 

Have you released the segmentation code and pre-trained models, if so where can we find it?

**Comment by ahatamiz** [comment]
We have released the [detection code](https://github.com/NVlabs/GCVit/tree/main/detection). Hopefully this can be useful.
