### ISSUE TITLE
Hi， Where can I download GC_ViT-B_384 pretrained weight ?

### ISSUE THREAD

**Issue by ross-Hr** [NVlabs/GCVit#38]
Hi ,
  Could you please share the pretrained model of GC_ViT-B_384 in IN1-K ?

**Comment by ahatamiz** [comment]
Hi @ross-Hr 

Thanks for the comment. We will release GC ViT-L_384 weights soon. Although this model is pre-trained on ImageNet21K and fine-tuned on 1K. Currently, we don't have GC ViT-B_384 on ImageNet-1K. But it could be a nice addition. 

I will post the updates regarding the new models soon.

**Comment by ross-Hr** [comment]
That would be great!
Expect new models!

By the way, can you add a feature return function in model? It may be used when distilling knowledge in object detection.

**Comment by ahatamiz** [comment]
Thanks for the suggestion. Sure, we will indeed release object detection repository with support for MaskRCNN, DINO, etc. very soon.

**Comment by ross-Hr** [comment]
I see that the model has been updated and the pre-training weights will be available for download soon?

**Comment by ahatamiz** [comment]
Hi @ross-Hr 

Please check the new model weights. We have added additional 21K weights which includes 384x384 as well.

**Comment by ross-Hr** [comment]
Congratulation! 
Great job!
