### ISSUE TITLE
Third-Party JAX/Flax implementation

### ISSUE THREAD

**Issue by BobMcDear** [NVlabs/GCVit#43]
Hello,

I am the developer of [flaim](https://github.com/BobMcDear/flaim), a library of pre-trained vision models for the JAX/Flax ecosystem, which includes GC ViT as one of its available architectures. I would appreciate it if you would consider mentioning flaim in the third-pary implementations section of the README.

Best,
Borna

**Comment by ahatamiz** [comment]
Hi Borna,

Thanks for the great efforts in including GC ViT into flaim. We have included it into the list of third-party implementations. 

Cheers,
Ali

**Comment by BobMcDear** [comment]
Wonderful, thank you as well.

All the best,
Borna
