### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by vztu** [NVlabs/GCVit#5]
Hi thanks for sharing the great work.

I am kindly wondering whether you are aware of our recent work that also proposes to use serial global-local attention? I am grateful if you can add a discussion if you happen to update it: [MaxViT: Multi-Axis Vision Transformer](https://arxiv.org/abs/2204.01697)

**Comment by ahatamiz** [comment]
Hi @vztu

Thank you for bringing your work to our attention. We will add it to the updated version of our paper. 

Best,
