### ISSUE TITLE
Questions about Installation

### ISSUE THREAD

**Issue by jczzp** [NVlabs/GCVit#8]
Hi thanks for sharing the great work. Some problems encountered during installation. README.md said "This repository is compatible with NVIDIA PyTorch docker nvcr>=21.06", my confusion is whether “NVIDIA PyTorch docker” is necessary and whether it is possible to simply install the correct Pytorch instead of installing “NVIDIA PyTorch docker”. 
Can you provide the complete requirements includes the version of Pytorch and other dependencies required for the project?
Looking forward to your reply, thank you!

**Comment by ahatamiz** [comment]
Hi @jczzp 

Thanks for your interest in our work. I have updated the dependencies for Pytorch and any other packages that this project uses. 

Best
